// Auto-generated by scripts/generate_protocol.mjs. Do not edit by hand.
// Source of truth: protocol/protocol_definitions.json.

export enum MsgType {
  RegisterUser = 0,
  RegisterUserReturn = 1,
  Login = 2,
  LoginSuccessReturn = 3,
  LoginFailedReturn = 4,
  SendMsg = 5,
  ReceiveMsg = 6,
  UserOnline = 7,
  UserOffline = 8,
  CreateGroup = 9,
  CreateGroupReturn = 10,
  SearchGroup = 11,
  SearchGroupReturn = 12,
  JoinGroup = 13,
  JoinGroupReturn = 14,
  LeaveGroup = 15,
  SendGroupMsg = 16,
  ReceiveGroupMsg = 17,
  UserJoinGroup = 18,
  UserLeaveGroup = 19,
  Heartbeat = 20,
  HeartbeatAck = 21,
  OfflineMessages = 22,
  Logout = 23,
  RequestHistory = 24,
  HistoryResponse = 25,
  SendFile = 26,
  ReceiveFile = 27,
  FileTransferDone = 28,
  AIRequest = 29,
  AIResponse = 30,
  AIStreamChunk = 31,
  UserProfileUpdate = 32,
  SystemBroadcast = 33,
}

export type ContentType = 'text' | 'image' | 'file' | 'system';
export type AIRequestType = 'summarize' | 'translate' | 'search' | 'chat';
export type ProtocolStatus = 'ok' | 'error' | 'failed' | 'start' | 'done';

export interface UserInfo {
  id: number;
  nickname: string;
  headId?: number;
  status?: ProtocolStatus;
}

export interface GroupInfo {
  groupId: number;
  name: string;
  hostId?: number;
  users?: UserInfo[];
}

export interface ProtocolMessageBase {
  type: MsgType;
  timestamp?: number;
  msg_id?: string;
}

export interface RegisterUserMessage extends ProtocolMessageBase {
  type: MsgType.RegisterUser;
  password: string;
  nickname: string;
  headId?: number;
}

export interface RegisterUserReturnMessage extends ProtocolMessageBase {
  type: MsgType.RegisterUserReturn;
  status: ProtocolStatus;
  id?: number;
  msg?: string;
  code?: number;
}

export interface LoginMessage extends ProtocolMessageBase {
  type: MsgType.Login;
  id: number;
  password: string;
}

export interface LoginSuccessReturnMessage extends ProtocolMessageBase {
  type: MsgType.LoginSuccessReturn;
  id: number;
  nickname: string;
  headId: number;
  friends?: UserInfo[];
  groups?: GroupInfo[];
  users?: UserInfo[];
}

export interface LoginFailedReturnMessage extends ProtocolMessageBase {
  type: MsgType.LoginFailedReturn;
  status: ProtocolStatus;
  msg: string;
  code?: number;
}

export interface SendMsgMessage extends ProtocolMessageBase {
  type: MsgType.SendMsg;
  fromId: number;
  toId: number;
  msg: string;
  content_type?: ContentType;
  reply_to?: string;
}

export interface ReceiveMsgMessage extends ProtocolMessageBase {
  type: MsgType.ReceiveMsg;
  fromId: number;
  toId: number;
  msg: string;
  id?: number;
  nickname?: string;
  headId?: number;
  content_type?: ContentType;
  reply_to?: string;
}

export interface UserOnlineMessage extends ProtocolMessageBase {
  type: MsgType.UserOnline;
  id: number;
  nickname?: string;
  headId?: number;
}

export interface UserOfflineMessage extends ProtocolMessageBase {
  type: MsgType.UserOffline;
  id: number;
  nickname?: string;
}

export interface CreateGroupMessage extends ProtocolMessageBase {
  type: MsgType.CreateGroup;
  hostId: number;
  name: string;
  hostNickname?: string;
  hostHeadId?: number;
}

export interface CreateGroupReturnMessage extends ProtocolMessageBase {
  type: MsgType.CreateGroupReturn;
  status: ProtocolStatus;
  groupId?: number;
  name?: string;
  msg?: string;
  code?: number;
}

export interface SearchGroupMessage extends ProtocolMessageBase {
  type: MsgType.SearchGroup;
  name: string;
  limit?: number;
}

export interface SearchGroupReturnMessage extends ProtocolMessageBase {
  type: MsgType.SearchGroupReturn;
  groups: GroupInfo[];
  status?: ProtocolStatus;
  msg?: string;
}

export interface JoinGroupMessage extends ProtocolMessageBase {
  type: MsgType.JoinGroup;
  id: number;
  groupId: number;
}

export interface JoinGroupReturnMessage extends ProtocolMessageBase {
  type: MsgType.JoinGroupReturn;
  status: ProtocolStatus;
  groupId: number;
  users?: UserInfo[];
  msg?: string;
  code?: number;
}

export interface LeaveGroupMessage extends ProtocolMessageBase {
  type: MsgType.LeaveGroup;
  id: number;
  groupId: number;
}

export interface SendGroupMsgMessage extends ProtocolMessageBase {
  type: MsgType.SendGroupMsg;
  fromId: number;
  groupId: number;
  msg: string;
  content_type?: ContentType;
  reply_to?: string;
}

export interface ReceiveGroupMsgMessage extends ProtocolMessageBase {
  type: MsgType.ReceiveGroupMsg;
  fromId: number;
  groupId: number;
  msg: string;
  nickname?: string;
  headId?: number;
  content_type?: ContentType;
  reply_to?: string;
}

export interface UserJoinGroupMessage extends ProtocolMessageBase {
  type: MsgType.UserJoinGroup;
  id: number;
  groupId: number;
  nickname?: string;
  headId?: number;
}

export interface UserLeaveGroupMessage extends ProtocolMessageBase {
  type: MsgType.UserLeaveGroup;
  id: number;
  groupId: number;
  nickname?: string;
}

export interface HeartbeatMessage extends ProtocolMessageBase {
  type: MsgType.Heartbeat;
}

export interface HeartbeatAckMessage extends ProtocolMessageBase {
  type: MsgType.HeartbeatAck;
  status: ProtocolStatus;
}

export interface OfflineMessagesMessage extends ProtocolMessageBase {
  type: MsgType.OfflineMessages;
  messages: Record<string, unknown>[];
}

export interface LogoutMessage extends ProtocolMessageBase {
  type: MsgType.Logout;
  id: number;
}

export interface RequestHistoryMessage extends ProtocolMessageBase {
  type: MsgType.RequestHistory;
  id: number;
  toId?: number;
  groupId?: number;
  limit?: number;
  cursor?: string;
}

export interface HistoryResponseMessage extends ProtocolMessageBase {
  type: MsgType.HistoryResponse;
  messages: Record<string, unknown>[];
  cursor?: string;
  has_more?: boolean;
}

export interface SendFileMessage extends ProtocolMessageBase {
  type: MsgType.SendFile;
  fromId: number;
  file_name: string;
  file_size: number;
  file_hash: string;
  toId?: number;
  groupId?: number;
  msg?: string;
}

export interface ReceiveFileMessage extends ProtocolMessageBase {
  type: MsgType.ReceiveFile;
  fromId: number;
  file_name: string;
  file_size: number;
  file_hash: string;
  toId?: number;
  groupId?: number;
  msg?: string;
}

export interface FileTransferDoneMessage extends ProtocolMessageBase {
  type: MsgType.FileTransferDone;
  status: ProtocolStatus;
  file_hash: string;
  msg?: string;
  code?: number;
}

export interface AIRequestMessage extends ProtocolMessageBase {
  type: MsgType.AIRequest;
  request_id: string;
  ai_type: AIRequestType;
  msg: string;
}

export interface AIResponseMessage extends ProtocolMessageBase {
  type: MsgType.AIResponse;
  request_id: string;
  status: ProtocolStatus;
  msg?: string;
  code?: number;
}

export interface AIStreamChunkMessage extends ProtocolMessageBase {
  type: MsgType.AIStreamChunk;
  request_id: string;
  chunk_index: number;
  is_final: boolean;
  msg: string;
}

export interface UserProfileUpdateMessage extends ProtocolMessageBase {
  type: MsgType.UserProfileUpdate;
  id: number;
  nickname?: string;
  headId?: number;
}

export interface SystemBroadcastMessage extends ProtocolMessageBase {
  type: MsgType.SystemBroadcast;
  msg: string;
  content_type?: ContentType;
  status?: ProtocolStatus;
  code?: number;
}

export type ProtocolMessage =
  RegisterUserMessage |
  RegisterUserReturnMessage |
  LoginMessage |
  LoginSuccessReturnMessage |
  LoginFailedReturnMessage |
  SendMsgMessage |
  ReceiveMsgMessage |
  UserOnlineMessage |
  UserOfflineMessage |
  CreateGroupMessage |
  CreateGroupReturnMessage |
  SearchGroupMessage |
  SearchGroupReturnMessage |
  JoinGroupMessage |
  JoinGroupReturnMessage |
  LeaveGroupMessage |
  SendGroupMsgMessage |
  ReceiveGroupMsgMessage |
  UserJoinGroupMessage |
  UserLeaveGroupMessage |
  HeartbeatMessage |
  HeartbeatAckMessage |
  OfflineMessagesMessage |
  LogoutMessage |
  RequestHistoryMessage |
  HistoryResponseMessage |
  SendFileMessage |
  ReceiveFileMessage |
  FileTransferDoneMessage |
  AIRequestMessage |
  AIResponseMessage |
  AIStreamChunkMessage |
  UserProfileUpdateMessage |
  SystemBroadcastMessage;

export const MSG_TYPE_NAMES: Record<MsgType, string> = {
  [MsgType.RegisterUser]: 'registerUser',
  [MsgType.RegisterUserReturn]: 'registerUserReturn',
  [MsgType.Login]: 'login',
  [MsgType.LoginSuccessReturn]: 'loginSuccessReturn',
  [MsgType.LoginFailedReturn]: 'loginFailedReturn',
  [MsgType.SendMsg]: 'sendMsg',
  [MsgType.ReceiveMsg]: 'receiveMsg',
  [MsgType.UserOnline]: 'userOnline',
  [MsgType.UserOffline]: 'userOffline',
  [MsgType.CreateGroup]: 'createGroup',
  [MsgType.CreateGroupReturn]: 'createGroupReturn',
  [MsgType.SearchGroup]: 'searchGroup',
  [MsgType.SearchGroupReturn]: 'searchGroupReturn',
  [MsgType.JoinGroup]: 'joinGroup',
  [MsgType.JoinGroupReturn]: 'joinGroupReturn',
  [MsgType.LeaveGroup]: 'leaveGroup',
  [MsgType.SendGroupMsg]: 'sendGroupMsg',
  [MsgType.ReceiveGroupMsg]: 'receiveGroupMsg',
  [MsgType.UserJoinGroup]: 'userJoinGroup',
  [MsgType.UserLeaveGroup]: 'userLeaveGroup',
  [MsgType.Heartbeat]: 'heartbeat',
  [MsgType.HeartbeatAck]: 'heartbeatAck',
  [MsgType.OfflineMessages]: 'offlineMessages',
  [MsgType.Logout]: 'logout',
  [MsgType.RequestHistory]: 'requestHistory',
  [MsgType.HistoryResponse]: 'historyResponse',
  [MsgType.SendFile]: 'sendFile',
  [MsgType.ReceiveFile]: 'receiveFile',
  [MsgType.FileTransferDone]: 'fileTransferDone',
  [MsgType.AIRequest]: 'aiRequest',
  [MsgType.AIResponse]: 'aiResponse',
  [MsgType.AIStreamChunk]: 'aiStreamChunk',
  [MsgType.UserProfileUpdate]: 'userProfileUpdate',
  [MsgType.SystemBroadcast]: 'systemBroadcast',
};

export function isValidMsgType(value: number): value is MsgType {
  return Number.isInteger(value) && value >= MsgType.RegisterUser && value <= MsgType.SystemBroadcast;
}

