import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const definitionPath = path.join(root, 'protocol', 'protocol_definitions.json');
const definitions = JSON.parse(fs.readFileSync(definitionPath, 'utf8').replace(/^\uFEFF/, ''));
const checkOnly = process.argv.includes('--check');

function pascalToInterface(name) {
  return `${name}Message`;
}

function schemaForField(fieldName) {
  const field = definitions.fields[fieldName];
  if (!field) {
    throw new Error(`Unknown protocol field: ${fieldName}`);
  }
  return structuredClone(field.schema);
}

function schemaFor(message) {
  const required = ['type', ...message.required];
  const fieldNames = new Set(['type', ...definitions.commonFields, ...message.required, ...message.optional]);
  const properties = {};
  for (const fieldName of fieldNames) {
    properties[fieldName] = fieldName === 'type'
      ? { const: message.value }
      : schemaForField(fieldName);
  }

  const schema = {
    $schema: definitions.schemaDraft,
    $id: `${definitions.schemaBaseId}${message.schemaName}.schema.json`,
    title: `LanChat ${message.schemaName}`,
    type: 'object',
    additionalProperties: false,
    required,
    properties,
    $defs: {
      user: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'nickname'],
        properties: {
          id: schemaForField('id'),
          nickname: schemaForField('nickname'),
          headId: schemaForField('headId'),
          status: schemaForField('status')
        }
      },
      group: {
        type: 'object',
        additionalProperties: false,
        required: ['groupId', 'name'],
        properties: {
          groupId: schemaForField('groupId'),
          name: schemaForField('name'),
          hostId: schemaForField('hostId'),
          users: schemaForField('users')
        }
      }
    }
  };

  if (message.anyOf) {
    schema.anyOf = message.anyOf.map((requiredGroup) => ({ required: requiredGroup }));
  }

  return schema;
}

function tsTypeFor(fieldName) {
  const field = definitions.fields[fieldName];
  if (!field) {
    throw new Error(`Unknown protocol field: ${fieldName}`);
  }
  return field.ts;
}

function generateTypes() {
  const names = Object.fromEntries(definitions.messages.map((message) => [message.value, message.schemaName]));
  const lines = [];
  lines.push('// Auto-generated by scripts/generate_protocol.mjs. Do not edit by hand.');
  lines.push('// Source of truth: protocol/protocol_definitions.json.');
  lines.push('');
  lines.push('export enum MsgType {');
  for (const message of definitions.messages) {
    lines.push(`  ${message.name} = ${message.value},`);
  }
  lines.push('}');
  lines.push('');
  lines.push("export type ContentType = 'text' | 'image' | 'file' | 'system';");
  lines.push("export type AIRequestType = 'summarize' | 'translate' | 'search' | 'chat';");
  lines.push("export type ProtocolStatus = 'ok' | 'error' | 'failed' | 'start' | 'done';");
  lines.push('');
  lines.push('export interface UserInfo {');
  lines.push('  id: number;');
  lines.push('  nickname: string;');
  lines.push('  headId?: number;');
  lines.push('  status?: ProtocolStatus;');
  lines.push('}');
  lines.push('');
  lines.push('export interface GroupInfo {');
  lines.push('  groupId: number;');
  lines.push('  name: string;');
  lines.push('  hostId?: number;');
  lines.push('  users?: UserInfo[];');
  lines.push('}');
  lines.push('');
  lines.push('export interface ProtocolMessageBase {');
  lines.push('  type: MsgType;');
  lines.push('  timestamp?: number;');
  lines.push('  msg_id?: string;');
  lines.push('}');
  lines.push('');

  for (const message of definitions.messages) {
    const interfaceName = pascalToInterface(message.name);
    const optionalOnly = new Set(message.optional);
    const fields = [...message.required, ...message.optional];
    lines.push(`export interface ${interfaceName} extends ProtocolMessageBase {`);
    lines.push(`  type: MsgType.${message.name};`);
    for (const fieldName of fields) {
      const optional = optionalOnly.has(fieldName) ? '?' : '';
      lines.push(`  ${fieldName}${optional}: ${tsTypeFor(fieldName)};`);
    }
    lines.push('}');
    lines.push('');
  }

  lines.push('export type ProtocolMessage =');
  definitions.messages.forEach((message, index) => {
    const suffix = index === definitions.messages.length - 1 ? ';' : ' |';
    lines.push(`  ${pascalToInterface(message.name)}${suffix}`);
  });
  lines.push('');
  lines.push('export const MSG_TYPE_NAMES: Record<MsgType, string> = {');
  for (const message of definitions.messages) {
    lines.push(`  [MsgType.${message.name}]: '${names[message.value]}',`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export function isValidMsgType(value: number): value is MsgType {');
  lines.push('  return Number.isInteger(value) && value >= MsgType.RegisterUser && value <= MsgType.SystemBroadcast;');
  lines.push('}');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function writeOrCheck(filePath, content) {
  const normalized = content.replace(/\r\n/g, '\n');
  if (checkOnly) {
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n') : '';
    if (existing !== normalized) {
      throw new Error(`${path.relative(root, filePath)} is out of date. Run node scripts/generate_protocol.mjs.`);
    }
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, normalized, 'utf8');
}

for (const message of definitions.messages) {
  const schemaPath = path.join(root, 'protocol', 'schemas', `${message.schemaName}.schema.json`);
  writeOrCheck(schemaPath, `${JSON.stringify(schemaFor(message), null, 2)}\n`);
}

writeOrCheck(path.join(root, 'protocol', 'message_types.ts'), generateTypes());

console.log(checkOnly ? 'Protocol generated files are up to date.' : 'Protocol schemas and TypeScript types generated.');


